
package.path    = package.path..";../?.lua"
local dirtools  = require("tools.vfs.dirtools").init("sokol%-luajit")

--_G.SOKOL_DLL    = "sokol_debug_dll"
local sapp      = require("sokol_app")
sg              = require("sokol_gfx")
local slib      = require("sokol_libs") -- Warn - always after gfx!!

local utils     = require("utils")

local ffi       = require("ffi")

------------------------------------------------------------------------------------------------------------

local tiny 		= require('editor.tiny-ecs')
local tinysrv	= require('editor.tiny-ecs-server')

local tinsert 	= table.insert

------------------------------------------------------------------------------------------------------------

local worldmanager = {
	worlds = {},
	worlds_lookup = {},
	systems = {},
	systems_lookup = {},
	entities = {},
	entities_lookup = {},
	cameras_lookup = {},
}

-- --------------------------------------------------------------------------------------

local function init()

	tinysrv.init()
	tinysrv.setWorlds(worldmanager.worlds)
	tinysrv.setEntities(worldmanager.entities, worldmanager.entities_lookup, worldmanager.cameras_lookup)
	tinysrv.setSystems(worldmanager.systems)    

    local desc = ffi.new("sg_desc[1]")
    desc[0].environment = slib.sglue_environment()
    desc[0].logger.func = slib.slog_func
    desc[0].disable_validation = false
    sg.sg_setup( desc )
    print("Sokol Is Valid: "..tostring(sg.sg_isvalid()))

    local cmd = [[start "" http://localhost:9190/index.html]]
    io.popen(cmd, "r")
end


-- --------------------------------------------------------------------------------------

local function input(event) 
end


-- --------------------------------------------------------------------------------------

local function frame()

    -- /* NOTE: the vs_params_t struct has been code-generated by the shader-code-gen */
    local w         = sapp.sapp_widthf()
    local h         = sapp.sapp_heightf()
    local t         = (sapp.sapp_frame_duration() * 60.0)

	-- Handle direct world swapping
	tinysrv.current_world = worldmanager.current_world
	for k,v in pairs(worldmanager.worlds) do
		v:update(dt)
	end
	tinysrv.update(dt)

    -- Display frame stats in console.
    -- hutils.show_stats()
end

-- --------------------------------------------------------------------------------------

local function cleanup()
    sg.sg_shutdown()

	tinysrv.final()
	tiny.clearEntities(worldmanager.current_world)
	tiny.clearSystems(worldmanager.current_world)    
end

-- --------------------------------------------------------------------------------------

local app_desc = ffi.new("sapp_desc[1]")
app_desc[0].init_cb     = init
app_desc[0].frame_cb    = frame
app_desc[0].cleanup_cb  = cleanup
app_desc[0].event_cb    = input
app_desc[0].width       = 1920
app_desc[0].height      = 1080
app_desc[0].window_title = "editor - sokol"
app_desc[0].fullscreen  = false
app_desc[0].icon.sokol_default = true 
app_desc[0].enable_clipboard = true
app_desc[0].logger.func = slib.slog_func 

sapp.sapp_run( app_desc )

-- --------------------------------------------------------------------------------------
